### ISSUE TITLE
Some questions about structure and contributing 

### ISSUE THREAD

**Issue by EgorWeders** [jmattaa/laser#10]
1. Its not ok to have include dir in src dir, especially for external usage. 
Your makefile located at root and have longer path to headers than to sources. If you make two dirs at root (include, src) it will be more readable and understandable.
 Example
  Now: 
  clang-format -i $(SRC_DIR)/*.c $(SRC_DIR)/include/*.h
  Will be 
  clang-format -i $(PROJECT_DIR)/src/*.c $(PROJECT_DIR)/include/*.h
Example with path to git module
  Now:
  src/git/include
  Will be
  include/git and src/git

2. It will be better to receive depth for recursive print from args and use default value if arg missing
 
I can rearrange directory and make pr for you if you approve this idea

Sry for my english, i hope you will get it.

**Comment by EgorWeders** [comment]
https://cliutils.gitlab.io/modern-cmake/chapters/basics/structure.html

**Comment by jmattaa** [comment]
I approve the idea of rearranging the directory. Why it was arranged like this from the beginning is that laser was meant to be a personal project and all my personal projects have been arranged this way. 

As for the recursive print depth, I don't really seem to understand what you mean. Do you mean using the recursive flag like this: 
```sh 
lsr --recursive=X
```
Where X will be the depth it will search for?
