### ISSUE TITLE
Not correct typechecking for files

### ISSUE THREAD

**Issue by EgorWeders** [jmattaa/laser#25]
Magic number approach doesn't work with empty files and files with malformed content
![изображение](https://github.com/user-attachments/assets/99eeff76-b883-49dd-b9f3-19b6802973d0)

**Comment by EgorWeders** [comment]
You can depend on filename extension and show parsed type as additional info
Example for file with tar content:
<LASER_COLOR_MEDIA>tarFileExample.jpeg</LASER_COLOR_MEDIA> (tar content)

**Comment by EgorWeders** [comment]
For file viewer filename must be more important than content.

**Comment by EgorWeders** [comment]
Possible solution:
Check filename extension (maybe with another env variable)
if it fails , check content for magic number.

**Comment by jmattaa** [comment]
Sounds like a grate idea! Though I don't really understand what you mean if it fails, if the file has no extension then we check the magic numbers?

**Comment by EgorWeders** [comment]
> Sounds like a grate idea! Though I don't really understand what you mean if it fails, if the file has no extension then we check the magic numbers?

Yep

**Comment by EgorWeders** [comment]
Maybe something like plugins will be a good idea , plugin for file coloring , info and etc. With dlopen from plugin dir for example.

**Comment by EgorWeders** [comment]
https://github.com/jmattaa/laser/pull/28
