### ISSUE TITLE
Bug: recursive option in short format with other flags

### ISSUE THREAD

**Issue by jmattaa** [jmattaa/laser#29]
https://github.com/jmattaa/laser/blob/8bd554916a7ede43c3686dc52f0563424e1d6ff0/src/utils.c#L52-L64

Running for example `lsr -rS` will cause the program to ignore the `-S` flag. But running `-Sr` works. 

Expected functionality
`lsr -rS` and `lsr -Sr` should behave the same.

**Comment by EgorWeders** [comment]
Its because s flag does not support arguments, but r does. line with getopt_long(argc, argv, "aFDSGr::l", long_args, NULL). I will try to fix it by falling to next argument case if r gets not a number.

**Comment by EgorWeders** [comment]
By the way, flags must chain with delimiter like - or -- (-r -S but not -rS). Maybe its not bug at all

**Comment by EgorWeders** [comment]
In future you can add numerical flags, and it will broke all complex parsing system for args like -r10S -rS 10

**Comment by EgorWeders** [comment]
You want to support fast "flags" (smth like -rSfabc) , its better to add separate option for it , like 
`lsr --lflag rSa` and parse it in  getopt check loop from optarg pointer
